### ISSUE TITLE
Cannot set property 'debug' of undefined thrown when using puppeteer version 1.7.0

### ISSUE THREAD

**Issue by jrdavismaine** [nswbmw/puppeteer-debug#2]
I am no longer able to use this library after upgrading puppeteer to version 1.7.0. Any attempt to run a puppeteer script results in the error  `Cannot set property 'debug' of undefined`. 

Please see steps to replicate for more information.

**Steps to replicate**
1. Install puppeteer version 1.62 and the latest version of this library.
```
npm install puppeteer@1.6.2
npm install puppeteer-debug@latest
```

2. Execute the below script. Chromium will launch and a debug session will be initiated.
```
const puppeteer = require('puppeteer-debug');
(async() => {
    const browser = await puppeteer.launch({ headless: false} );
    const page = await browser.newPage();
    await page.debug();
    await browser.close();
})();
```

3. Update puppeteer to the latest version, e.g. `npm install puppeteer@latest`. Run the script in step 2, the below error is thrown.
```
PS C:\puppeteerdebug> node .\test.js
C:\puppeteerdebug\node_modules\puppeteer-debug\index.js:6
Page.prototype.debug = debug
                     ^

TypeError: Cannot set property 'debug' of undefined
    at Object.<anonymous> (C:\puppeteerdebug\node_modules\puppeteer-debug\index.js:6:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\puppeteerdebug\test.js:1:81)
    at Module._compile (module.js:635:30)
```

**Comment by nswbmw** [comment]
I bump v2.0.0, use `vm.createContext()` instead of `eval()`, more flexible & keep context.
